### ISSUE TITLE
Users flow: users dashboard

### ISSUE THREAD

**Issue by tcp** [OpenMined/pygrid-admin#15]
## Feature Description
Build a page that shows all users registered in the PyGrid Node.

**Warning** ⚠️ 
There is no UI in Framer. Be (careful and) creative.

**Comment by infern018** [comment]
Can I work on this issue @tcp ?

**Comment by tcp** [comment]
@infern018 can I suggest a more [important issue](https://github.com/OpenMined/pygrid-admin/issues/27)?

**Comment by infern018** [comment]
> @infern018 can I suggest a more [important issue](https://github.com/OpenMined/pygrid-admin/issues/27)?

Yeah sure, please do
