### ISSUE TITLE
Header component

### ISSUE THREAD

**Issue by tcp** [OpenMined/pygrid-admin#27]
## Feature Description
The Header allows users to navigate between the sections. Upon selecting one of the major sections (e.g. Datasets), the Header transitions to the variant of the section. The back button in the header takes the user back to the main dashboard.

Here are the sections:

- Datasets: `Datasets`, `Requests`, `Tensors`
- Models
- Users: `Users`, `Groups`, `Roles`
- Infrastructure: `Infrastructure`, `Nodes`, `Workers`
- Finances
- Settings: `Settings`, `Infrastructure`, `Associations`, `Monetization`, `Branding`

Models and Finances have no subsection and, consequently, no transition.

A started for the Header exists in [src/components/header/index.tsx](https://github.com/OpenMined/pygrid-admin/blob/dev/src/components/header/index.tsx) and that should be used as the starting point for this issue. The PyGrid logo and Header height have been implemented.

This is how it should look like: [Framer link](https://framer.com/share/PyGrid-Admin--sqLTLbsgzBzUix5DmV7g#r7YHL2hBg).

**Comment by infern018** [comment]
Can you assign this to me?

**Comment by tcp** [comment]
Take it away @infern018 :)

**Comment by infern018** [comment]
![image](https://user-images.githubusercontent.com/52378712/108618610-7cc85000-7445-11eb-80bb-f1651b574871.png)
i am getting this error while running npm run dev, can u help me out with this?

**Comment by infern018** [comment]
I had a doubt, that where from where can I retrieve the data like how many datasets, models, users are there, so that i can add those in the main header component?
