### ISSUE TITLE
Datasets flow: Dataset view (view, edit, delete)

### ISSUE THREAD

**Issue by tcp** [OpenMined/pygrid-admin#42]
## Feature Description
View and manage dataset details.

**Route**: `/datasets/:id`

Users will reach this page by clicking on one of the dataset cards in `pygrid-admin/datasets`.

Dataset tags are shown under the description. There is no need to reorder them. Keep the same order that comes in the API response.

Tensors info is displayed inside the `data` tab.

A first attempt at the UI has been implemented [here](https://github.com/OpenMined/pygrid-admin/blob/dev/src/pages/datasets/[slug].tsx). Please modify as needed.

<img src="https://user-images.githubusercontent.com/802731/109709191-2325fb00-7b94-11eb-92dd-de6e6ba4dde0.gif" width="300" />

Please import [@reach-ui/dialog](https://github.com/reach/reach-ui/tree/main/packages/dialog) for a creating the modal for editing or deleting a dataset.

| op | endpoint |
| --- | --- |
| create | `POST /dcfl/datasets` |
| read | `GET /dcfl/datasets/:id` |
| update | `PUT /dcfl/datasets/:id` |
| delete | `DELETE /dcfl/datasets/:id` |

**Comment by ariannmichael** [comment]
I would like to take this issue
