### ISSUE TITLE
Add proper typings

### ISSUE THREAD

**Issue by tcp** [OpenMined/pygrid-admin#74]
## What?
Typings are a bit off and we would benefit from having all of the main resources properly typed.

## Why?
This is a simple refactor that helps us build all the screens we need and send the correct payload to PyGrid.

## Breakdown
- Delete `src/types/api-responses.ts`
- Remove `I{type}` (e.g. IRole, IGroup, IDataset, IWorker...)
- Add new meaningful types (e.g. PyGridWorker)
- Match typings to Domain API resources
- Create `src/types/index.ts` and export all types from there

**Comment by victorperezc** [comment]
How should we handle the `src/types/api-responses.ts`? Removing this will affect the entire axis api calls

**Comment by tcp** [comment]
Let's get rid of it. We can use the actual meaningful types (User, Groups, Datasets, etc) instead of a type for each API response.
